org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.0.0
maven_group=dev.fixpot47
archives_base_name=pvp-hitboxes

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_version=0.160.6+26.3
modmenu_version=21.0.0-alpha.1
cloth_config_version=26.3.+
